/* translation of file "abstract.k" */
/* generated by:
 *  @(#)$Author: Kimwitu++ version 2.3.11 (C) 1998-2007 Humboldt-University of Berlin $
 */
#ifndef KC_FUNCTIONS_abstract_HEADER
#define KC_FUNCTIONS_abstract_HEADER
#include "k.h"    // in case a user forgets


namespace kc {

} // namespace kc

#endif // !  KC_FUNCTIONS_abstract_HEADER

